import type { Metadata } from 'next'
import { Geist_Mono, Inter, Montserrat, IBM_Plex_Sans_Thai, Kanit } from 'next/font/google'
import './globals.css'
import Navbar from './_components/Navbar'
import { ClerkProvider } from '@clerk/nextjs'
import { currentUser } from '@clerk/nextjs/server'
import { UserStoreProvider } from './_providers/user-store-provider'
import { mergeCurrentUser } from './_stores/user-store'
import UserModel from '@/models/User'
import { connectMongoose } from './_lib/mongoose'

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
})

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

const sans = IBM_Plex_Sans_Thai({
    variable: '--font-sans',
    subsets: ['thai', 'latin'],
    weight: ['400', '500', '600', '700'],
})

const heading = Kanit({
    variable: '--font-heading',
    subsets: ['thai', 'latin'],
    weight: ['500', '600', '700'],
})

export const metadata: Metadata = {
    title: 'Match Desk',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const clerkUser = await currentUser()
    let currentUserProfile = null

    if (clerkUser?.id) {
        await connectMongoose()
        currentUserProfile = await UserModel.findOne({ clerkUserId: clerkUser.id }).lean()
    }

    return (
        <ClerkProvider>
            <html lang='en'>
                <body
                    className={`${sans.variable} ${heading.variable} ${geistMono.variable} flex h-dvh flex-col antialiased`}>
                    <UserStoreProvider initialState={{ currentUser: mergeCurrentUser(clerkUser, currentUserProfile) }}>
                        <Navbar />
                        <main className='flex-1 min-h-0 overflow-y-auto'>{children}</main>
                    </UserStoreProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}
